source: "site"
destination: "_site"
permalink: "/:categories/:year/:month/:title.html"
defaults:
  - scope:
      path: "/events"
    values:
      layout: "event"
  - scope:
      path: ""
    values:
      layout: "default"
      segment_token: "FAFG7bcxwMR1l6ljIj1oPLBx9dkSFWlc"

assets:
  sources:
    - assets/js
    - assets/scss

collections:
  contributors:
    slug: sarah-mei
    name: Sarah Mei
    twitter: sarahmei
    website: http://sarahmei.com
